# Generated by Django 4.0.3 on 2022-05-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='joiningdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
