# Generated by Django 4.0.3 on 2022-05-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_registration_joiningdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_scrapdatahistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('History', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
