# Generated by Django 4.0.3 on 2022-05-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_scrapdatahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_scrapdatahistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.user_registration'),
        ),
    ]
