# Generated by Django 4.0.3 on 2022-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_scrapdatahistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_scrapdatahistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
