# Generated by Django 4.0.3 on 2022-05-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_scrapdatahistory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=240, null=True)),
                ('Describe', models.CharField(max_length=2404, null=True)),
                ('url', models.CharField(max_length=240, null=True)),
                ('filez', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
